[package]
name = "my-near-cli-dialoguer"
version = "0.1.0"
authors = ["FroVolod <frol_off@meta.ua>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.7"
